apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: togglemaster
data:
  PORT: "8001"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: togglemaster
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service:8001"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: togglemaster
data:
  PORT: "8003"
  AUTH_SERVICE_URL: "http://auth-service:8001"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AWS_REGION: "us-east-1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"